---
- name: Kubernetes Setup for worker nodes
  hosts: all
  become: yes  # Run tasks with elevated privileges
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install dependencies for Kubernetes
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present

    - name: Adding directory for keyrings
      file:
        path: /etc/apt/keyrings
        state: directory

    - name: Add Kubernetes public signing key
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes apt repository
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"

    - name: Update apt repository (post Kubernetes repo addition)
      apt:
        update_cache: yes

    - name: Install Kubernetes tools (kubeadm, kubelet, kubectl)
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Enable kubelet service
      systemd:
        name: kubelet
        state: started
        enabled: yes
